### ISSUE TITLE
Merge with gradle-miniconda-plugin?

### ISSUE THREAD

**Issue by punya** [JetBrains/gradle-python-envs#1]
Hi @traff, I'm the author of gradle-miniconda-plugin. The changes/enhancements you've made seem pretty cool, and I'd have accepted PRs for them to the original project. While you're obviously within your legal rights to fork or copy the code, I'd appreciate if you could contribute your changes back and we could build a Python + Gradle community together.

Thanks!

**Comment by traff** [comment]
Hi @punya, I am happy to hear from you. Actually I have nothing against contributing back to the gradle-miniconda-plugin. It was a great help for me. I decided to fork it because I wasn't sure that such a huge change could be accepted as a PR to the initial project, because it became incompatible. I could make a PR, do you think that it should be done with the gradle-python-envs exact current state or any changes to preserve compatibility should be done?

**Comment by punya** [comment]
Hi @traff, I'm glad to hear you're up for contributing your changes back! I think it's okay to break backwards compatibility in order to accommodate new features, but I'd like the existing integration tests fixed up and new integration tests added.

cc @mnazbro for additional thoughts.

**Comment by mnazbro** [comment]
I agree with Punya on the compatibility requirements. We can break whatever makes sense to get new features. I'll be the point of contact on getting any changes into gradle-miniconda-plugin.

**Comment by traff** [comment]
The current project has now a greater scope than installing miniconda. It handles CPython, Jython, PyPy, and IronPython now. And the name "gradle-python-envs" seems to represent that better than "gradle-miniconda-plugin". Also it is being developed a bit more intensive at the moment.
